### ISSUE TITLE
ERB isn't evaluated in remote recipes

### ISSUE THREAD

**Issue by bryanp** [kenn/sunzi#33]
Just encountered this myself, and haven't put an enormous amount of thought into it. I do think though that this should be possible and was planning to fix and/or add the capability.

Is there some underlying reason this can't / shouldn't be added?

**Comment by kenn** [comment]
I revisited this issue, but decided that evaluating a remote recipe as code is bad for both structural and security reasons. It's not something we could do for a nice-to-have feature, the consequence could potentially be huge.

If you have a compelling use case that cannot be achieved otherwise, please let me know.
